### ISSUE TITLE
Out of date and contradictory accessibility information for IBM Cloud

### ISSUE THREAD

**Issue by sharitrewin** [ibm-cloud-docs/overview#1]
1. What are the details of the issue you're experiencing?

Information about IBM Cloud accessibility seems to be out of date or contradictory. Specifically:

> IBM Cloud uses the latest W3C Standard, [WAI-ARIA 1.0](http://www.w3.org/TR/wai-aria/)

[Version 1.1](https://www.w3.org/TR/wai-aria-1.1/) of the WAI-ARIA standard has been out since 2017, and version 1.2 is almost final. 

> to ensure compliance to US Section 508 and [Web Content Accessibility Guidelines (WCAG) 2.0](http://www.w3.org/TR/WCAG20/)

[WCAG 2.1](https://www.w3.org/TR/WCAG21/) has been the current recommendation since 2018 and the accessibility conformance report for IBM Cloud Continuous Delivery - 3Q 2021 is reporting against WCAG 2.1, not 2.0, so this reference may need to be updated to point to WCAG 2.1.

> use the latest release of your screen reader in combination with the latest Firefox web browser 

> If you are using a screen reader with the IBM Cloud web user interface or product documentation, use the latest version of Internet Explorer

The information about which browser to use with a screen reader is contradictory. It is surprising to see IE recommended since it does not support WAI-ARIA.

2. Is this issue in reference to a specific page? If so, please provide a link.

https://cloud.ibm.com/docs/overview/accessibility?topic=overview-accessibility-platform#accessibility-ibm

3. Do you have a suggestion about how to resolve the issue?

- Verify which version of WAI-ARIA is supported and either update to the newer version or delete 'the latest'.
- Verify the version of WCAG used for testing is WCAG 2.1 and update the reference.
- Check which browsers are supported for screen reader users and resolve the contradiction, or do not mention specific browsers.

**Comment by mekaufman** [comment]
@sharitrewin Thank you for your feedback. The topic has been updated to reflect the latest standards listed as being met in our current VPAT. I also clarified that Firefox is recommended as the browser for using a screen reader.
