### ISSUE TITLE
Secure Gateway - Script needs to be updated

### ISSUE THREAD

**Issue by knobutan** [ibm-cloud-docs/overview#1]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
The script will not work as CF stopped supporting `src: process.env.CF_INSTANCE_IP`
CF team recommended to use the following method to obtain its IP address.
```
> cf ssh APPNAME
vcap@XXXX:~$ curl https://api.myip.com
{"ip":"130.198.18.239","country":"Australia","cc":"AU"}
```

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/SecureGateway?topic=SecureGateway-iptables-rules#iptables-dynamic-ips

3. Do you have a suggestion about how to resolve the issue?
Take it down for now and renew it if it worth it.

**Comment by knobutan** [comment]
Maybe I submitted this issue to a wrong path

**Comment by mekaufman** [comment]
@knobutan Thank you for the feedback. I've routed this issue to the correct team.
