### ISSUE TITLE
Broken link in Terms page

### ISSUE THREAD

**Issue by pmarsh2** [ibm-cloud-docs/overview#10]
The link in the first paragraph of the [IBM Cloud Terms of Use](https://cloud.ibm.com/docs/overview?topic=overview-terms) page appears to be broken.

The URL as rendered is: [http://www-03.ibm.com/software/sla/sladb.nsf/sla/bm?_ga=2.56833066.1271209253.1604422393-1133305139.1604422393](http://www-03.ibm.com/software/sla/sladb.nsf/sla/bm?_ga=2.56833066.1271209253.1604422393-1133305139.1604422393). The query parameter, _ga=2.568... causes the target page on the SLA site to return a "General Error, Invalid URL Exception" message.

The query parm. is not in the page markdown so is presumably being added elsewhere?

**Comment by cdmauney** [comment]
Broken link fixed.
