### ISSUE TITLE
Link on AppId home page does not work

### ISSUE THREAD

**Issue by jigneshkvp** [ibm-cloud-docs/overview#10]
Hello,

The link to [Mobile App with serverless backend](https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-serverless-mobile-backend) on the [AppId home page](https://www.ibm.com/cloud/app-id) does not work.

**Comment by mekaufman** [comment]
Thank you for reporting the issue. I've moved this over for the App ID link to get fixed here: https://github.com/ibm-cloud-docs/appid/issues/389
