### ISSUE TITLE
Service Level Agreements link is not working

### ISSUE THREAD

**Issue by RahulMetangale** [ibm-cloud-docs/overview#10]
1. What are the details of the issue you're experiencing? SLA Link is no longer working. Earlier it used to load pdf document.

2. Is this issue in reference to a specific page? If so, please provide a link. yes please refer to [this](https://cloud.ibm.com/docs/overview?topic=overview-slas) page. And try clicking on [Service Level Agreement Link]([IBM Cloud Service Level Agreements](https://www.ibm.com/support/customer/csol/terms/?id=i126-9268&lc=en&_gl=1*1ngixgo*_ga*NDA5ODQwODIzLjE2OTM0NjA5MzM.*_ga_FYECCCS21D*MTY5NDEzOTYzOS4zNy4xLjE2OTQxMzk4MjQuMC4wLjA.#detail-document))

3. Do you have a suggestion about how to resolve the issue? Please update the link

**Comment by mekaufman** [comment]
@RahulMetangale Thank you for your feedback. I have tested out the link on my end, and the PDF is loading for me. Could you check again and let me know if it's still not loading for you? It did take a few moments to fully load.
