### ISSUE TITLE
IBM Cloud® encrypts all data in transit is in correct

### ISSUE THREAD

**Issue by mraquinn** [ibm-cloud-docs/overview#12]
https://cloud.ibm.com/docs/overview?topic=overview-key-encryption#:~:text=IBM%20Cloud%C2%AE%20encrypts%20all,IBM%20Cloud%C2%AE%20Activity%20Tracker.

Are these statements reflected in the DSP?

**Comment by mekaufman** [comment]
@mraquinn Thank you for the feedback. I see you also opened an internal issue that we'll use to track required updates.
