### ISSUE TITLE
Hong Kong and India Missing From Service Availability Docs

### ISSUE THREAD

**Issue by gganendran** [ibm-cloud-docs/overview#12]
Hi,

Hong Kong and India are missing from the service availability docs: https://cloud.ibm.com/docs/overview?topic=overview-services_region

Can you please update this doc to reflect both these regions?

Thanks,

Gaj

**Comment by mekaufman** [comment]
Hong Kong and India are available in the topic. Thank you for the feedback.
![image](https://user-images.githubusercontent.com/13648625/119829166-f5b5c880-bec8-11eb-9abb-d097a956c194.png)
