### ISSUE TITLE
Please update this certifcations/training page

### ISSUE THREAD

**Issue by RogerSnook** [ibm-cloud-docs/overview#13]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
 - This page mentions some out of date certifications and a new IBM Center for Cloud Training ICCT has been launched.

2. Is this issue in reference to a specific page? If so, please provide a link.
- There's a V2 foundations course now, however, there's also a whole landing page for the ICCT:
external: https://www.ibm.com/training/cloud/jobroles
Internal https://icct.yourlearning.ibm.com

3. Do you have a suggestion about how to resolve the issue?
- Suggest working with Michael Barton/Portland/IBM from the ICCT on the correct content.

**Comment by mekaufman** [comment]
The page has been updated. Thanks!

**Comment by RogerSnook** [comment]
@mekaufman - thanks. While it is good to mention the specific certs - I would strongly recommend ALSO including the TOP LEVEL link as MORE of that training and certification is planned and is evolving quickly.
