### ISSUE TITLE
 Availability SLA table is for the IBM Cloud Platform is out of date

### ISSUE THREAD

**Issue by ClaireTurner** [ibm-cloud-docs/overview#15]
Hi there - I am opening this issue on the advice of Bill Wentworth ( RSET support team lead) - 
This IBM Cloud Document is incorrect:
https://cloud.ibm.com/docs/overview?topic=overview-slas&locale=en#avail-downtime

The document is not clear that the Availability SLA table is for the IBM Cloud Platform itself and that individual services might have different SLA requirements.
The information in the table in the Availability SLA table is out of date. If they are going to continue to have this topic in the docs, which I don't recommend, they need to keep it in sync with section 3.2.2 of the IBM Cloud Service Description here:
http://www-03.ibm.com/software/sla/sladb.nsf/pdf/6605-20/$file/i126-6605-20_10-2020_en_US.pdf

As a suggestion BIll recommended - If you are going to keep that table in the docs, it might be best to say that it is used for illustration purposes only and see the IBM Cloud Service Description.

**Comment by mekaufman** [comment]
We have updated this topic. Thank you for the feedback.
