### ISSUE TITLE
Issue: Opening Terms and Conditions Page. It Keeps loading and never finishes loading. 

### ISSUE THREAD

**Issue by mrglovett3** [ibm-cloud-docs/overview#16]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing? I cannot open the Terms & Conditins page to get the documents I need. 

2. Is this issue in reference to a specific page? If so, please provide a link.
https://www.ibm.com/support/customer/csol/terms/?id=i126-9268&lc=en#detail-document

4. Do you have a suggestion about how to resolve the issue? No, I need help ASAP.

**Comment by mekaufman** [comment]
Hi @mrglovett3, The link you provided above is working for me. Could you try again, and please let me know if you still can't access the Terms page?

**Comment by mrglovett3** [comment]
Mekaufman,

It is working now. Thank you!

George Lovett
Analytics & Cognitive Solutions
Advisory Data & AI West
[AaZ3mWZ0VHRawAAAABJRU5ErkJggg==]
Phone: 1-602-579-6452
E-mail: ***@***.******@***.***>

From: mekaufman ***@***.***>
Date: Wednesday, November 8, 2023 at 4:52 PM
To: ibm-cloud-docs/overview ***@***.***>
Cc: George Lovett ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/overview] Issue: Opening Terms and Conditions Page. It Keeps loading and never finishes loading. (Issue #16)
Hi @mrglovett3, The link you provided above is working for me. Could you try again, and please let me know if you still can't access the Terms page? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2M-q6PXc4NIRUo84cgqv5pUljXZrW6jU-zkeDIAblLdTaXL-dvOSXLmBghiIYNcEQbJ1efTeTaMnU5-F4cRpS4B_Yavy99ydsVR_Ap4807iikps$>   ‌
ZjQcmQRYFpfptBannerEnd

Hi @mrglovett3<https://github.com/mrglovett3>, The link you provided above is working for me. Could you try again, and please let me know if you still can't access the Terms page?
