### ISSUE TITLE
"Description:Unable to locate datacenter with name FRA02 [Backend Error:Failed to get datacenter name 'FRA02'from SL" when creating a pvc

### ISSUE THREAD

**Issue by Delagrace** [ibm-cloud-docs/overview#17]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by mekaufman** [comment]
@Delagrace If you're still experiencing an issue with VPC, you might need to open a support case for additional help. Alternatively, you can review the the VPC documentation available here: https://cloud.ibm.com/docs/vpc.
