### ISSUE TITLE
Documentation of IBM

### ISSUE THREAD

**Issue by Ittacipriya** [ibm-cloud-docs/overview#18]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by mekaufman** [comment]
Hi @Ittacipriya, I don't see any comments about an issue you're experiencing with IBM Cloud docs, so I'm closing this issue. Please reopen it with a comment, if needed.
