### ISSUE TITLE
penetration test 

### ISSUE THREAD

**Issue by tronca82** [ibm-cloud-docs/overview#2]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
 details on penetration test for VPC :  what is allowed and what it isn't  if a customer needs to perform a pen test?  why is not mentioned the need to submit a  ticket to ACS-security informing about the planned activity( I mean the penetration test) 

3. Is this issue in reference to a specific page? If so, please provide a link.

4. Do you have a suggestion about how to resolve the issue?

**Comment by mekaufman** [comment]
@tronca82 Thank you for this feedback. I have reached out internally and we'll work to address your feedback.
