### ISSUE TITLE
Syntax error in Ingress resource creation examples

### ISSUE THREAD

**Issue by Matthew-Wroblewski** [ibm-cloud-docs/overview#2]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

Errors when following steps in below links due to the syntax not matching the current API version in the Ingress resource.

2. Is this issue in reference to a specific page? If so, please provide a link.

https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4#ingress-roks4-public-3
https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4#priv-se-pub-controller-4
https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4#ingress-roks4-private-4
https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4#priv-se-priv-controller-3

3. Do you have a suggestion about how to resolve the issue?

The version of the API was updated to apiVersion: networking.k8s.io/v1 - and the old version deprecated.
However, the syntax wasn't updated to match the new API. I had a user who followed this guide but received errors when he tried to deploy the ingress.

The updated syntax in YAML should be closer to the example here: https://kubernetes.io/docs/concepts/services-networking/ingress/
Specifically :
```
backend:
    serviceName: <app1_service>
    servicePort: 80
```

Now should appear like this or else the ingress resource will receive an error when it's applied in the next step:
```
backend:
    service:
        name: test
        port:
            number: 80
```

The below links are most likely a better visualization of proper indentation for the YAML.
It should look closer to: https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
or https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#alb-comm-create-ingress-resource
For more details: https://docs.openshift.com/container-platform/4.10/rest_api/network_apis/ingress-networking-k8s-io-v1.html

**Comment by mekaufman** [comment]
@Matthew-Wroblewski Thank you so much for opening this issue. I've reopened this issue in the repo for OpenShift team so that they can address the issue in docs.
