### ISSUE TITLE
Topic January 2024 price changes - error in Italian page

### ISSUE THREAD

**Issue by massimocaprinali** [ibm-cloud-docs/overview#20]
There is an error in the internationalization of this page in Italian
- https://cloud.ibm.com/docs/overview?topic=overview-price-adjustments

First row of the table, Dallas and so on, report 80% instead 0%.

Locale EN
<img width="799" alt="price EN" src="https://github.com/ibm-cloud-docs/overview/assets/23118648/13a0fb63-bbf1-4123-9ed6-2b92cd44dccb">

Locale IT
<img width="802" alt="price IT" src="https://github.com/ibm-cloud-docs/overview/assets/23118648/a8c5bd12-49b9-4aeb-88ce-1b37062a4f40">

**Comment by mekaufman** [comment]
Thank you for reporting this. The page has been updated to correct the percentage.
