### ISSUE TITLE
Missing SAO01 AZ on Americas Data Centers list

### ISSUE THREAD

**Issue by victorshinya** [ibm-cloud-docs/overview#21]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing? **Missing the SAO01 (Sao Paulo AZ) on the list**.

2. Is this issue in reference to a specific page? If so, please provide a link. **Yes, specifically on Data Centers' section (https://cloud.ibm.com/docs/overview?topic=overview-locations#data-centers)**.

3. Do you have a suggestion about how to resolve the issue? **Yes, I am submitting a PR in order to fix this issue**.

**Comment by mekaufman** [comment]
Thank you for the feedback. SAO01 is currently listed.
