### ISSUE TITLE
Dead Links on https://cloud.ibm.com/docs/overview?topic=overview-slo&locale=en

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/overview#21]
The following links on this pages are not actual:
- URL:  https://cloud.ibm.com/docs/overview?topic=overview-slo
- Chapter: Containers services

Dead Links
- IBM Cloud Kubernetes Service - https://cloud.ibm.com/docs/containers?topic=containers-ha
- Red Hat OpenShift on IBM Cloud - https://cloud.ibm.com/docs/openshift?topic=openshift-ha

Please check all links of this website if they are actual.

Feedback: Please implement a dead link detection.

**Comment by mekaufman** [comment]
The links have been fixed. Thank you for reporting the issue.
