### ISSUE TITLE
Issue in the RACI table - IBM responsible for VPC service - like security group and its configuration??

### ISSUE THREAD

**Issue by skuronen** [ibm-cloud-docs/overview#24]
Table 1. defines the shared responsibilities for IaaS products, which is misleading and may give a wrong impression to the customer. 

Virtual network is defined as "Network resources such as VLAN, VPC, subnets, or IPs provided by classic infrastructure and VPC services that are ordered and managed through IBM Cloud."

This whole area, and its responsibility is set to IBM. These include

- Incident and Operations Management
- Change Management
- Identity and Access Management
- Security and Regulation Compliance

When virtual network defines VPC services, this could lead the customer to think that IBM is responsible for the security configurations. I.e. how the customer has configured the specific VPC service like security group or acl. Or how they have secured the subnet/VLAN in Classic.

Other cloud providers define the responsibility more clearly, e.g. https://aws.amazon.com/compliance/shared-responsibility-model/ where e.g. customer "OS/network/firewall configurations" are customer responsibilities.

The table mode presented does not directly support this or maybe there should be a new row stating "the configurations", or a different model. There is not a single sentence that the customer is responsible for these configurations/rules or the correctness of these. The same applies e.g. for COS buckets and how they configure these as likely many other.

**Comment by mekaufman** [comment]
Thank you for the feedback. The topic has been reviewed and updated to include updated shared responsibilities in the tables as well as notes about customer configurations and disaster recovery responsibilities.
