### ISSUE TITLE
Update IBM Professional Certification exams to a newer version

### ISSUE THREAD

**Issue by victorshinya** [ibm-cloud-docs/overview#26]
The [Getting certified in IBM Cloud](https://cloud.ibm.com/docs/overview?topic=overview-cloud-certifications) page on IBM Cloud Docs does not have the newer version of IBM Cloud certification. 

- IBM Certified Solution Advisor - IBM Cloud Foundations V1 has updated to [IBM Certified Solution Advisor - IBM Cloud Foundations V2](https://www.ibm.com/certify/cert?id=C0002201).
- IBM Certified Application Developer - Cloud Solutions v3 has updated to [IBM Certified Professional Developer - Cloud v4](https://www.ibm.com/certify/cert?id=C0001904).
- IBM Certified Architect - Cloud Solutions v3 has updated to [IBM Certified Solution Architect - Cloud v4](https://www.ibm.com/certify/cert?id=C0001402).

And there is a new certification exam, called [IBM Certified Professional SRE - Cloud v1](https://www.ibm.com/certify/cert?id=C0007800) which defines a new Job Role mapped by IBM, the Site Reliability Engineer professional.

**Comment by mekaufman** [comment]
The page has been updated with the newer versions of the exams. Thanks!
