### ISSUE TITLE
https://cloud.ibm.com/docs/overview?topic=overview-locations SZR list is out-of-date

### ISSUE THREAD

**Issue by feifeiliibm** [ibm-cloud-docs/overview#27]
The list of SZR list is not up-to-date. Please help to correct the list.

**Comment by mekaufman** [comment]
@feifeiliibm I am looking into this with an internal issue that I will send you via slack. However, based on the information I currently have the 2 listed SZRs are correct when you define an SZR as A region that consists of data centers that are located within one zone.
