### ISSUE TITLE
More information about how to find support

### ISSUE THREAD

**Issue by songololo** [ibm-cloud-docs/overview#28]
1. What are the details of the issue you're experiencing?

Unable to sign-up successfully and no contact options for reaching out for help from IBM (without working account).

2. Is this issue in reference to a specific page? If so, please provide a link.

Yes: the sign-up page:

<img width="639" alt="Screenshot 2021-05-25 at 00 35 35" src="https://user-images.githubusercontent.com/4347878/119419196-a10c2500-bcf1-11eb-9230-77a6c064a3b2.png">

3. Do you have a suggestion about how to resolve the issue?

Either an option for how to reach-out for support (without a working account) or else information in the docs about how to resolve potential issues when trying to sign-up for an account.

**Comment by mekaufman** [comment]
@songololo Thank you for your feedback. I've passed along this feedback and we are working to improve our docs and the experience in the console. In the meantime, try signing up in a private window as that might help. If you're still experiencing issues, please provide your email address and I can connect with you and try to get you some help.
