### ISSUE TITLE
Redirect the same page.

### ISSUE THREAD

**Issue by dineshchelladurai** [ibm-cloud-docs/overview#29]
There is an 3 days bootcamp conducted by IBM in my college. IBM gives code for 1 year free cloud services for students. So, after I login the cloud site    and enter the code I gives error and after some minutes it gives a message like code was applied successfully and it redirect the same page again ask that. I tried lot of times. I know the whole students working in that time. That's why there might be an issue. But, again I try that in my home. It shows errors again. There are lot of students getting this error. I think it is an issue. Kindly check it out.  I attached the page. It redirect again and again. 
![Screenshot_20240801_171150](https://github.com/user-attachments/assets/1a647cf7-338f-4e96-b500-1b8d4cd1cb7e)

**Comment by vws2013** [comment]
hi @dineshchelladurai ! I checked and see nothing wrong with the code or your account. Would you be able to try to apply the code again in an incognito browser. If you're still facing issues please feel free to reach out to the IBM SkillsBuild: https://skillsbuild.org/contact
