### ISSUE TITLE
Block Storage is missing from the Infrastructure offerings

### ISSUE THREAD

**Issue by vickmuir** [ibm-cloud-docs/overview#3]
1. What are the details of the issue you're experiencing? 
I don't see Block Storage listed in any of the tables in Service and infrastructure availability by location topic.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/overview?topic=overview-services_region

3. Do you have a suggestion about how to resolve the issue?
Please add Block Storage to every table that contains File Storage and IBM Cloud Backup. Block Storage is available in every location where File Storage is available.

**Comment by mekaufman** [comment]
Hi @vickmuir. This page is generated. I'll reach out to provide more information.
