### ISSUE TITLE
wrong term used to describe POP or Regio  "Market"

### ISSUE THREAD

**Issue by coldsync** [ibm-cloud-docs/overview#3]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
the use of the term market is wrong in "...Diverse dark fiber providers are used to connect every compute facility to the edge, and each edge site is connected to at least three adjacent IBM Cloud markets (with rare exception)." and "...through peering exchanges, in each market at each edge site."
2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/overview?topic=overview-zero-downtime
3. Do you have a suggestion about how to resolve the issue?
replace market with "region" or POP ?

**Comment by mekaufman** [comment]
@coldsync Thanks for the feedback. I'm reviewing this with our team and will be able to provide an update soon.

**Comment by mekaufman** [comment]
The topic has been updated after consulting with the team. Thank you again.
