### ISSUE TITLE
Can't close the image when it viewed in the Zoom Mode

### ISSUE THREAD

**Issue by yassersaidi** [ibm-cloud-docs/overview#30]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
Here, the problem is there is no way to escape or close the image
![Screenshot from 2024-08-13 14-01-51](https://github.com/user-attachments/assets/fa356434-2e3d-4412-93ce-2a7ff82350c9)

3. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/overview?topic=overview-locations
4. Do you have a suggestion about how to resolve the issue?
Add button to close the Zoom mode

**Comment by mekaufman** [comment]
@yassersaidi Thank you for reporting the issue. We're working to address the issue.

**Comment by mekaufman** [comment]
This issue has been resolved. Thank you for reporting it.
