### ISSUE TITLE
IBM Cloud Satellite

### ISSUE THREAD

**Issue by felix-yong** [ibm-cloud-docs/overview#31]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/satellite?topic=satellite-infrastructure-plan

### What do you think needs to be updated?

Why RHEL 9 is not supported?

**Comment by mekaufman** [comment]
I've routed this issue to the team who can help address the issue here: https://github.com/ibm-cloud-docs/satellite/issues/74. Thank you!
