### ISSUE TITLE
please help to modify or delete the URL "https://xxx.xxx.xxx.xxx"

### ISSUE THREAD

**Issue by zhenglei1984** [ibm-cloud-docs/overview#32]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
 https://cloud.ibm.com/apidocs/ibm-analytics-engine ? IBM need remove URL： https://xxx.xxx.xxx.xxx  contained in the page asap.  the website https://xxx.xxx.xxx.xxx  was the real website and include bad content.
 
2. Is this issue in reference to a specific page? If so, please provide a link.
 https://cloud.ibm.com/apidocs/ibm-analytics-engine 
 Example responses
Success example

> "jdbc:phoenix:thin:url=https://xxx.xxx.xxx.xxx:8443/gateway/default/avatica;authentication=BASIC;serialization=PROTOBUF",

3. Do you have a suggestion about how to resolve the issue?
Delete the URLhttps://xxx.xxx.xxx.xxx or  change the X to *

<img width="510" alt="WX20210804-161200@2x" src="https://user-images.githubusercontent.com/3394465/128150754-767bb223-8317-46cf-b001-c97869eb072a.png">

**Comment by mekaufman** [comment]
Thank you for the feedback. I've alerted the team and moved this issue to their area to address.
