### ISSUE TITLE
out of date content

### ISSUE THREAD

**Issue by raf95** [ibm-cloud-docs/overview#32]
### Which topic are you reporting about?

the entity extractor tool - demo video at https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-entity-extractor#entity-extractor-video 

### What do you think needs to be updated?

this does not exist in v2, seems to be v1 references, so expect this to be updated and reflect v2 functionality

**Comment by mekaufman** [comment]
I have routed this issue to the team who can help address the issue here: https://github.com/ibm-cloud-docs/discovery-data/issues/25. Thanks!
