### ISSUE TITLE
Auto Scale is supported in SAO

### ISSUE THREAD

**Issue by AliseATX** [ibm-cloud-docs/overview#35]
https://cloud.ibm.com/docs/overview?topic=overview-services_region

Thanks!

Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by mekaufman** [comment]
The table has been updated to reflect Auto Scale for VPC's availability in Sao Paulo. Thank you for reporting this issue.
