### ISSUE TITLE
Create a dedicated page to reference IBM Cloud Public Certification  

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/overview#39]
Most of IBM Cloud clients and partners asked whether we have certifications for IBM Cloud Public. We actually do but most of them have a hard time to find them. An easy way to address that would be to create a dedicated page such as http://cloud.ibm.com/certification. This page would reference the 3 majors certifications we have today:

1. IBM Certified Application Developer - Cloud Solutions v3 https://www.ibm.com/certify/cert?id=C0001903

1. IBM Cloud Solutions Architect v3 https://www.ibm.com/certify/exam?id=C1000-017

1. IBM Certified Architect - Cloud Solutions v3 https://www.ibm.com/certify/cert?id=C0001400

@jenschlot

**Comment by cdmauney** [comment]
Published at https://cloud.ibm.com/docs/overview?topic=overview-cloud-certifications.
