### ISSUE TITLE
Typo on https://cloud.ibm.com/docs/overview?topic=overview-locations

### ISSUE THREAD

**Issue by brendanonymous** [ibm-cloud-docs/overview#4]
Hi this is Brendan Lauck, I'm actually a dev with IBM Cloud. Had to sign in to my personal GH acct to get access to submit this issue. 

There's a small typo in [overview-locations](https://cloud.ibm.com/docs/overview?topic=overview-locations):

on that map, `jp-toc` should be `jp-tok`

If there's a better way to submit this issue internally, please slack me.

ibm email: brendanlauck@ibm.com
slack: brendan

**Comment by mekaufman** [comment]
@brendanonymous Thank you for reporting the issue. We're working to get it fixed today.

**Comment by mekaufman** [comment]
The graphic has been updated. Thanks again for your feedback.
