### ISSUE TITLE
a wrong URL reference on Text-To-Speech Getting Started Page

### ISSUE THREAD

**Issue by ushan** [ibm-cloud-docs/overview#40]
On the Text-To-SPeech resource page in the "Getting Started" section, there are wrong URLs in the text of the very bottom, API & "SDK reference." refers to "https://%7Bdomainname%7D/apidocs/text-to-speech" instead of a correct URL

**Comment by mekaufman** [comment]
@ushan Thanks for reporting this. I've opened an issue for the Text to speech team [here](https://github.com/ibm-cloud-docs/text-to-speech/issues/144).
