### ISSUE TITLE
Private ip ranges for the schematics workers in us-east and us-south region are missing

### ISSUE THREAD

**Issue by IgnazioT** [ibm-cloud-docs/overview#41]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
I received a case from a Customer asking for private ip ranges for the schematics workers in us-east and us-south region. 
Looking at  https://cloud.ibm.com/docs/schematics?topic=schematics-allowed-ipaddresses doc page, IPs for us-east and us-south regions are missing. Please add IPs

2. Is this issue in reference to a specific page? If so, please provide a link.

 https://cloud.ibm.com/docs/schematics?topic=schematics-allowed-ipaddresses

3. Do you have a suggestion about how to resolve the issue?

Referring to case CS2683447  and GIT Issue https://github.ibm.com/blueprint/schematics-support-tickets/issues/435 needs to add the following IPs:

wdc04 - 10.148.98.0/26
wdc06 - 10.189.2.128/26, 10.189.2.16/29
wdc07 - 10.191.181.64/26

dal12 - 10.185.16.64/26
dal10 - 10.95.173.64/26
dal13 - 10.220.38.64/26

**Comment by mekaufman** [comment]
@IgnazioT Thank you for reporting this. I have forwarded this issue internally to our Schematics team to address.
