### ISSUE TITLE
zero_downtime.md uses old SLA model

### ISSUE THREAD

**Issue by pmarsh2** [ibm-cloud-docs/overview#47]
As of August 1st 2019, the Service Level Agreement for IaaS Services was updated to use a percentage available in a month model, rather than the old 30 minutes of continuous downtime model.

The exact definitions are available in the [IBM Cloud Service Description, Section 3](http://www-03.ibm.com/software/sla/sladb.nsf/pdf/6605-18/$file/i126-6605-18_08-2019_en_US.pdf).

Can this page be updated to reflect the new SLA model please?

**Comment by cdmauney** [comment]
Updated. Thanks for the feedback.
