### ISSUE TITLE
Compliance Report Request

### ISSUE THREAD

**Issue by daviddelozier** [ibm-cloud-docs/overview#5]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?  The link for the compliance report request is no longer working 

3. Is this issue in reference to a specific page? If so, please provide a link. https://cloud.ibm.com/classic/security/compliancereport/request

4. Do you have a suggestion about how to resolve the issue?
I need a new link so I can request a compliance report for a customer request

Thank you!

**Comment by mekaufman** [comment]
Hi @daviddelozier. Are you logged in to your IBM Cloud account? The link looks to be working for me. Please let me know what you're experiencing when you're logged in and clicking that link.

**Comment by daviddelozier** [comment]
When I click the link it takes me to the IBM login and I log in (even though I’m already logged in) and then it redirects me to the main Cloud Dashboard rather than the form to submit a ticket to receive a SOC2 report.  If you can tell me where to go from the main dashboard I can do that as well, but cannot seem to find the right path

David DeLozier
CarbonHelix | VP of Sales
214-277-2061
***@***.******@***.***>
Register your opportunities here!<http://www.carbonhelix.net/register>
[signature_3845820326]

From: mekaufman ***@***.***>
Date: Monday, March 27, 2023 at 10:18 AM
To: ibm-cloud-docs/overview ***@***.***>
Cc: David DeLozier ***@***.***>, Mention ***@***.***>
Subject: Re: [ibm-cloud-docs/overview] Compliance Report Request (Issue #5)

Hi @daviddelozier<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdaviddelozier&data=05%7C01%7Cdavid.delozier%40carbonhelix.net%7C40f008ff4ccd4a522bc408db2ed66fb8%7Ca17206604a284f47999e7b954becc0d4%7C0%7C0%7C638155270803960566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HzdJ0cmpB2xuQ%2BvQKhfQm9eLKz0mcUtSs6wiHEmIkS0%3D&reserved=0>. Are you logged in to your IBM Cloud account? The link looks to be working for me. Please let me know what you're experiencing when you're logged in and clicking that link.

**Comment by mekaufman** [comment]
Hi @daviddelozier I'm sorry to hear the direct link isn't working for you. Try the following steps and let me know if you're still experiencing an issue:

1. Log in to IBM Cloud
2. Click the Menu icon (3 horizontal bars icon) in the upper-left corner from your dashboard view.
3. Select Classic infrastructure > Compliance Report.

You can see the menu path here:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/13648625/228338311-7296d252-9c34-48fd-bf9d-80cad8352620.png">

**Comment by daviddelozier** [comment]
Hi –

For some reason, I do not see that option.  We have the classic infrastructure tab but it does not expand like the others.  When I click into it, it’s asking me to upgrade my account.  We have a large spend already on baremetal (at least $25k a month) so this doesn’t make any sense.
***@***.***

***@***.***

David DeLozier
CarbonHelix | VP of Sales
214-277-2061
***@***.******@***.***>
Register your opportunities here!<http://www.carbonhelix.net/register>
[signature_2473762615]

From: mekaufman ***@***.***>
Date: Tuesday, March 28, 2023 at 1:50 PM
To: ibm-cloud-docs/overview ***@***.***>
Cc: David DeLozier ***@***.***>, Mention ***@***.***>
Subject: Re: [ibm-cloud-docs/overview] Compliance Report Request (Issue #5)

Hi @daviddelozier<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdaviddelozier&data=05%7C01%7Cdavid.delozier%40carbonhelix.net%7Cfa4b338f39474cb1726108db2fbd5761%7Ca17206604a284f47999e7b954becc0d4%7C0%7C0%7C638156262505864819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YySXIgzAlv1MhhiLJEYHR7IecEJKsjjJHQZ%2BBZig3TY%3D&reserved=0> I'm sorry to hear the direct link isn't working for you. Try the following steps and let me know if you're still experiencing an issue:

  1.  Log in to IBM Cloud
  2.  Click the Menu icon (3 horizontal bars icon) in the upper-left corner from your dashboard view.
  3.  Select Classic infrastructure > Compliance Report.

You can see the menu path here:
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13648625%2F228338311-7296d252-9c34-48fd-bf9d-80cad8352620.png&data=05%7C01%7Cdavid.delozier%40carbonhelix.net%7Cfa4b338f39474cb1726108db2fbd5761%7Ca17206604a284f47999e7b954becc0d4%7C0%7C0%7C638156262505864819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EgUx9jWz6SQl8iWX7bNxN0MQHt47oz%2FZ3XOoq06V0xA%3D&reserved=0>

**Comment by mekaufman** [comment]
@daviddelozier Thanks for testing it out on your end. I'm reaching out to some colleagues to see how we can help. In the meantime, we do have compliance reports available on this page: https://www.ibm.com/cloud/compliance/global, but it sounds like maybe you're looking for something else.

**Comment by mekaufman** [comment]
@daviddelozier It look as though it might be a permission issue. Can you check that you have an IAM access policy with the Viewer role on the Billing service? If you don't have this level of access, can you ask an administrator to assign it to you, and then try the page again.

You can find what access you're assigned by going logging in and going to Manage > Access (IAM) > Users, then select your name. From there, you can click the Access tab to review your assigned IAM policies.

**Comment by mekaufman** [comment]
Hi @daviddelozier. I am closing this issue, but if you're still experiencing an issue, please reopen this issue and let us know how we can help. Thanks!
