### ISSUE TITLE
Docs index page should list Backup for VPC under storage section

### ISSUE THREAD

**Issue by bdubwalters** [ibm-cloud-docs/overview#5]
In the main index of IBM cloud catalog products under the storage section there should be a listing for 'Backup for VPC"  Currently only IBM Backup is listed, which is the Classic service. Also the docs for that service make no mention of Backup for VPC.  Given the strategic importance of VPC we should ensure that customers can find these new capabilities and that they get significant mention and attention whenever possible

-  All product docs / index  https://cloud.ibm.com/docs?tab=all-docs
- Backup Classic  https://cloud.ibm.com/docs/Backup?topic=Backup-getting-started#getting-started
- Backup for VPC https://cloud.ibm.com/docs/vpc?topic=vpc-backup-service-about

**Comment by mekaufman** [comment]
@bdubwalters Thank you for your feedback. I've opened an issue with the team who can make updates to the docs listed above here: https://github.com/ibm-cloud-docs/Backup/issues/12

**Comment by vickmuir** [comment]
The two products are not the same product with two different implementations. They serve the same purpose, but they are two different solutions entirely. In the same way as [Veeam on IBM Cloud](https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-veeamvm_overview) does backup and recover for VMWare, yet it is not a Storage product and not listed under Storage.
IBM Cloud Backup is based on Carbonite's Evault software and portal, and Backup software agents that are installed on virtual or bare-metal hosts which send data to the vaults.
Backup for VPC is actually just a snapshot of the VPC Storage volume. There's no separate 3rd-party software installed or portal involved. Backup for VPC is not listed under Storage in All Docs, but neither is Block Storage for VPC or File Storage for VPC. They are all included in Virtual Private Cloud (VPC) under Networking.
This probably could be a discussion with the Product/Offering Managers. Doug Petteway is the OM for Storage.
