### ISSUE TITLE
Explicit mapping of services to categories.

### ISSUE THREAD

**Issue by schoutene** [ibm-cloud-docs/overview#59]
1. What are the details of the issue you're experiencing?
The shared responsibilities page is very helpful for my client (BNP Paribas) and is being used internally at the client. It's however also generating confusion, on the exact mapping of our services to the categories of responsibilities in the page (IaaS, full mngt, self mngt, software). Everyone has their view, but we should be explicit. 

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/overview?topic=overview-shared-responsibilities

3. Do you have a suggestion about how to resolve the issue?
List (or link to a view of the catalog) on which services are considered IaaS, full mngt, self mngt, software.

**Comment by mekaufman** [comment]
@schoutene Thank you for providing the feedback. I have made an update to each section of the topic that helps to describe how to find each offering type in the category.  Also, as services start to provide their own documentation specific to just their service, they should be listing the category to which they belong. If you have additional feedback, feel free to reach out to me directly mtompki@us.ibm.com.
