### ISSUE TITLE
URLs not working - dead links

### ISSUE THREAD

**Issue by pvrbharg** [ibm-cloud-docs/overview#6]
This URL link is referencing two dead links shown below - under the heading of "How VPC differentiates from the classic infrastructure":
https://www.ibm.com/cloud/architecture/content/course/advanced-networking-for-vpc/vpc-vs-classic-infrastructure

The following two URL links are dead links:

https://cloud.ibm.com/docs/overview?topic=overview-compare-infrastructure&cm_mmc=IBMBluemixGarageMethod-_-MethodSite-_-10-19-15::12-31-18-_-overview-compare-infrastructure
https://cloud.ibm.com/docs/overview?topic=overview-compare-vpc-vpcoc&cm_mmc=IBMBluemixGarageMethod-_-MethodSite-_-10-19-15::12-31-18-_-overview-compare-vpc-vpcoc

**Comment by davidstacy** [comment]
will update, please let me know what the new text should look like.

**Comment by gudrun-wolfgram** [comment]
Here's the link for Comparing IBM Cloud infrastructure environments https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-compare-infrastructure

The Comparing compute generations in VPC topic doesn’t apply anymore. That was for when there was VPC Gen 1 and VPC Gen 2. VPC Gen 1 doesn’t exist anymore.

So the updated sentence can say, “For more information, see [Comparing IBM Cloud infrastructure environments](https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-compare-infrastructure).”

Looks like the following note should also be deleted…

Note: Although you have two VPC virtual server options, use only Gen 1 virtual servers if you need global data center presence, [Bring Your Own Key (BYOK)](https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-about#about-vpc-customer-managed-encryption&cm_mmc=IBMBluemixGarageMethod-_-MethodSite-_-10-19-15::12-31-18-_-vpc-block-storange-about#about-vpc-customer-managed-encryption) capability, or [IBM Cloud® Kubernetes Service integration](https://cloud.ibm.com/docs/vpc?topic=containers-vpc_ks_tutorial&cm_mmc=IBMBluemixGarageMethod-_-MethodSite-_-10-19-15::12-31-18-_-containers-vpc-ks-tutorial).

**Comment by mekaufman** [comment]
Thanks, Gudrun. @davidstacy Are you able to make these updates?

**Comment by mekaufman** [comment]
I confirmed that these courses are being removed, so the links will not be updated. However, the correct links are available above.
