### ISSUE TITLE
Hardware replacement SLA does not match Service Description

### ISSUE THREAD

**Issue by pmarsh2** [ibm-cloud-docs/overview#6]
The [Service Level Agreement](https://cloud.ibm.com/docs/overview?topic=overview-slas) page largely reflects what is in the [base Service Description](https://www-03.ibm.com/software/sla/sladb.nsf/latest/bm-6605) document.

In the Infrastructure hardware replacement and upgrade section, the Doc page lists the refunds for both >14 hours and >18 hours as 80%. This is incorrect. Per the Service Description, the refund level for >18 hours should be 100%

**Comment by pmarsh2** [comment]
PR --> https://github.com/ibm-cloud-docs/overview/pull/7

**Comment by mekaufman** [comment]
This page has been updated. Thanks for the feedback.
