### ISSUE TITLE
Figure 1. Multizone region (MZR) Distance between Zone need to be updated

### ISSUE THREAD

**Issue by teoks** [ibm-cloud-docs/overview#6]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
Figure 1. Multizone region (MZR) Distance between DC need to be updated 

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/overview?topic=overview-locations#table-mzr

3. Do you have a suggestion about how to resolve the issue?
Understand in MZR, distance between is more than ~10km, can we get this updated in the diagram?

**Comment by mekaufman** [comment]
Hi @teoks. Thank you for the feedback. I have checked in with our team and the distance is approximate as shown in the graphic as it might be below or above that 10 km distance, and that is accurate at this time.
