### ISSUE TITLE
i got error for the delivery pipeline

### ISSUE THREAD

**Issue by samruddhi812** [ibm-cloud-docs/overview#60]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by hlucey** [comment]
Hi @samruddhi812  are you an IBMer? If so, please reach out to me internally and I can help route you to the right team for this issue.

If you're not an IBMer, please open a support case here and our support team can get you squared away: https://cloud.ibm.com/unifiedsupport/supportcenter
