### ISSUE TITLE
Link to infrastructure architecture is broken

### ISSUE THREAD

**Issue by gangchen03** [ibm-cloud-docs/overview#62]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
When clicking 
```
Start with the infrastructure architecture External link icon to get a more in-depth overview of the three types of cloud environments.
```
The infrastructure architecture links to https://www.ibm.com/cloud/architecture/notfound?requestedUrl=%2Farchitectures%2Finfrastructure is broken.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/overview?topic=overview-it-ops#infrastructure-architecture

3. Do you have a suggestion about how to resolve the issue?
Fix the URL link

**Comment by hlucey** [comment]
Link is working.
