### ISSUE TITLE
Does Seoul zone have two data centers which are SEO01 and SEO02?

### ISSUE THREAD

**Issue by EunKyung-Kim** [ibm-cloud-docs/overview#63]
As far as I know, Seoul zone has a data center, SEO01.
When I try to create a VM through resource catalogue, the list of data centers shows only SEO01. But, this document describes Seoul zone has two data centers which are SEO01 and SEO02. I think that the document should be corrected.

Regards,
EunKyung Kim.

**Comment by cdmauney** [comment]
Updated: https://cloud.ibm.com/docs/overview?topic=overview-locations
