### ISSUE TITLE
Bad Data is present in this page - MZRs that don't exist yet, SZR sites that don't exist yet, and old DCs that are dead are showing up. 

### ISSUE THREAD

**Issue by bknapp-ibm** [ibm-cloud-docs/overview#65]
1. What are the details of the issue you're experiencing?

**bad data is present in the page**

2. Is this issue in reference to a specific page? If so, please provide a link.

`https://cloud.ibm.com/docs/overview?topic=overview-locations#mzr-table`

Both the SAO MZR and the Osaka MZR show up, and they should not show up yet. Likewise, SEO02 is showing up, and that's a POP

`https://cloud.ibm.com/docs/overview?topic=overview-locations#data-centers`

DAL01 is still showing up, and that DC has been EOLed and shut down. Raleigh 01 shows up, and that's not a cloud site. 

3. Do you have a suggestion about how to resolve the issue?

Needs to be updated to show the right info, and get the pre-release info back out of the page.

**Comment by cdmauney** [comment]
Updated: https://cloud.ibm.com/docs/overview?topic=overview-locations
