### ISSUE TITLE
Don't see a button that the text says I should see

### ISSUE THREAD

**Issue by douglin** [ibm-cloud-docs/overview#68]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
The document says "You must be logged in to your account to qualify for personalized onboarding. After you log in, a Get started button is displayed on this page."  I am logged into my PAYG account and do not see the button.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/overview?topic=overview-personalized-assistance&focusArea=WCP%20-%20Onboarding%20CSM

3. Do you have a suggestion about how to resolve the issue?

**Comment by cdmauney** [comment]
Button is displayed:

![image](https://user-images.githubusercontent.com/22623884/85044665-8f221980-b153-11ea-9733-8901618b819e.png)
