### ISSUE TITLE
Dead link in `Monitoring and Logging` page

### ISSUE THREAD

**Issue by mhmxs** [ibm-cloud-docs/overview#69]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

The URL on the page ends in 404, but if i remove the query from the URL the pages became available.

2. Is this issue in reference to a specific page? If so, please provide a link.

https://cloud.ibm.com/docs/cli?topic=cloud-cli-monitoring_logging => For more information, see `Monitoring in IBM Cloud`.

3. Do you have a suggestion about how to resolve the issue?

Nope

**Comment by cjcarpen** [comment]
This link has been updated! Thanks for opening an issue: https://cloud.ibm.com/docs/cli?topic=cli-monitoring_logging
