### ISSUE TITLE
URGENT: Brazil and Osaka MZR's Need to be removed from table - not live yet

### ISSUE THREAD

**Issue by janetell** [ibm-cloud-docs/overview#70]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

Incorrect content

2. Is this issue in reference to a specific page? If so, please provide a link.

https://cloud.ibm.com/docs/overview?topic=overview-locations&locale=en

3. Do you have a suggestion about how to resolve the issue?

Remove Brazil and Osaka from the MZR table, they are not live yet.   I also want to know who updated this table to put them in there, we need to correct that process

**Comment by cdmauney** [comment]
Updates are live.
