### ISSUE TITLE
Bug in spelling of city name

### ISSUE THREAD

**Issue by lucianocairesaraujo** [ibm-cloud-docs/overview#9]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
R: In the output of the watson assistant prompt, the city of São Paulo, Brazil, appeared with the following bug: So Paulo.
2. Is this issue in reference to a specific page? If so, please provide a link.
R: Yes. https://dataplatform.cloud.ibm.com/wx/prompts/templates/e9b5c6af-7edb-4921-adb1-9c7128916c5a?project_id=72d01337-4e7f-4d7e-957e-cf445523f112&context=wx&open_prompts=true
3. Do you have a suggestion about how to resolve the issue?
R: The expected result of this solution would be "São Paulo", because it is a city name.

**Comment by mekaufman** [comment]
@lucianocairesaraujo Thank you for the feedback. We'll get this routed to the correct team.
