### ISSUE TITLE
broken link https://cloud.ibm.com/docs/overview?topic=overview-terms

### ISSUE THREAD

**Issue by feifeiliibm** [ibm-cloud-docs/overview#9]
this first link on the subjected page is broken. 

Your IBM Cloud® account and any services that are ordered from the IBM Cloud are provided under the terms of the Service Description for IBM Cloud available at [http://www-03.ibm.com/software/sla/sladb.nsf/sla/bm?_ga=2.233141851.457042314.1604351173-884608094.1604351173&_gac=1.92254696.1603826795.Cj0KCQjwit_8BRCoARIsAIx3Rj5IZD1sNngW9UTh8kwvt-9TeQ3Up7fDnnAW8oWpq9m7hgP2Zuq6aNEaAjldEALw_wcB](http://www-03.ibm.com/software/sla/sladb.nsf/sla/bm ;) and one of the following base agreements:

**Comment by cdmauney** [comment]
Broken link fixed.
